# Generated by Django 2.0.5 on 2018-07-14 21:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_auto_series', models.BigAutoField(editable=False, help_text='Auto Increment ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', unique=True, verbose_name='Universal Unique Identifier')),
                ('title', models.CharField(help_text='Ex.: Title of place - House of Photographer Smith', max_length=128, verbose_name='Title')),
                ('street', models.CharField(blank=True, help_text='Ex.: Main Avenue', max_length=128, null=True, verbose_name='Street')),
                ('number', models.CharField(blank=True, help_text='Ex.: 1580', max_length=32, null=True, verbose_name='Number')),
                ('complement', models.CharField(blank=True, help_text='Ex.: Apartament 2B', max_length=128, null=True, verbose_name='Complement')),
                ('neighborhood', models.CharField(blank=True, help_text='Ex: Exhibition Vile', max_length=64, null=True, verbose_name='Neighborhood')),
                ('state', models.CharField(blank=True, help_text='Ex.: New York', max_length=64, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, help_text='Ex.: New York City', max_length=64, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, help_text='Ex.: United States of America', max_length=64, null=True, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, help_text='Ex.: 434093-4085485', max_length=32, null=True, verbose_name='Postal Code')),
                ('lat_and_long', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ex.: latitude 438974592318, longitude 9482375732', null=True, srid=4326, verbose_name='Latitude & Longitude')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
    ]
