# Generated by Django 2.0.5 on 2018-07-12 14:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('complement', models.CharField(blank=True, max_length=128)),
                ('neighborhood', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('lat_and_long', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
    ]
