# Generated by Django 2.0.5 on 2018-07-13 21:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, help_text='Ex.: New York City', max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='complement',
            field=models.CharField(blank=True, help_text='Ex.: Apartament 2B', max_length=128, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, help_text='Ex.: United States of America', max_length=64, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat_and_long',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ex.: latitude 438974592318, longitude 9482375732', null=True, srid=4326, verbose_name='Latitude & Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Ex: Exhibition Vile', max_length=64, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.CharField(blank=True, help_text='Ex.: 1580', max_length=32, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Ex.: 434093-4085485', max_length=32, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, help_text='Ex.: New York', max_length=64, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, help_text='Ex.: Main Avenue', max_length=128, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(help_text='Ex.: Title of place - House of Photographer Smith', max_length=128, verbose_name='Title'),
        ),
    ]
