# Generated by Django 2.0.5 on 2018-07-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180705_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
