# Generated by Django 2.0.5 on 2018-07-09 20:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto set field', primary_key=True, serialize=False, unique=True, verbose_name='Universal Unique Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto set field', verbose_name='Created in')),
                ('title', models.CharField(blank=True, help_text='Ex.: Aquisition from The Photographer...', max_length=256, null=True, verbose_name='Title')),
                ('date_start', models.DateField(blank=True, help_text='Choose a start date', null=True, verbose_name='Initial Date')),
                ('date_end', models.DateField(blank=True, help_text='Choose an final date - special for lending', null=True, verbose_name='Final Date')),
                ('abstract', models.TextField(blank=True, help_text='Ex.: this acquisition is composed by...', null=True, verbose_name='Abstract')),
                ('full_text', models.TextField(blank=True, help_text='Ex.: All itens in this acquisition...', null=True, verbose_name='Full Text')),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Other unstructured data of this collection', null=True, verbose_name='Other Data')),
                ('dealer', models.ManyToManyField(blank=True, help_text='Choose people who traded this asset', related_name='personDealer', to='person.Person', verbose_name='Dealer')),
            ],
            options={
                'verbose_name': 'Acquisition',
                'verbose_name_plural': 'Acquisitions',
            },
        ),
        migrations.CreateModel(
            name='AcquisitionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acquisition Method',
                'verbose_name_plural': 'Acquisition Methods',
            },
        ),
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto set field', verbose_name='Created in')),
                ('title', models.CharField(blank=True, help_text='Title of Management Unit', max_length=256, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='The description of Management Unit', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Management Unit',
                'verbose_name_plural': 'Management Units',
            },
        ),
        migrations.AddField(
            model_name='acquisition',
            name='method',
            field=models.ForeignKey(blank=True, help_text='Choose an Option', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.AcquisitionMethod', verbose_name='Aquisition Method'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='source',
            field=models.ManyToManyField(blank=True, help_text='Choose people who have been source to this acquisition', related_name='personSource', to='person.Person', verbose_name='Source'),
        ),
    ]
