# Generated by Django 2.0.5 on 2018-07-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionmethod',
            name='description',
            field=models.TextField(blank=True, help_text='The description of acquisition method', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='acquisitionmethod',
            name='title',
            field=models.CharField(blank=True, help_text='Type of acquisition method', max_length=128, verbose_name='Title'),
        ),
    ]
