# Generated by Django 2.0.5 on 2018-07-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='title',
            field=models.CharField(help_text='Ex.: Aquisition from The Photographer...', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='acquisitionmethod',
            name='title',
            field=models.CharField(help_text='Type of acquisition method', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='title',
            field=models.CharField(help_text='Title of Management Unit', max_length=256, verbose_name='Title'),
        ),
    ]
