# Generated by Django 2.0.5 on 2018-07-24 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180719_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
        migrations.AddField(
            model_name='acquisitionmethod',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
        migrations.AddField(
            model_name='managementunit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
    ]
