# Generated by Django 2.0.5 on 2018-07-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180627_1712'),
        ('management', '0003_auto_20180703_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aquisition',
            new_name='Acquisition',
        ),
        migrations.RenameModel(
            old_name='AquisitionMethod',
            new_name='AcquisitionMethod',
        ),
        migrations.AlterModelOptions(
            name='acquisition',
            options={'verbose_name': 'Acquisition', 'verbose_name_plural': 'Acquisitions'},
        ),
        migrations.AlterModelOptions(
            name='acquisitionmethod',
            options={'verbose_name': 'Acquisition Method', 'verbose_name_plural': 'Acquisition Methods'},
        ),
    ]
