# Generated by Django 2.0.5 on 2018-07-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20180703_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition',
            old_name='fulltext',
            new_name='full_text',
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='date_end',
            field=models.DateField(blank=True, help_text='Choose an final date - special for lending', null=True, verbose_name='Final Date'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='date_start',
            field=models.DateField(blank=True, help_text='Choose a start date', null=True, verbose_name='Initial Date'),
        ),
    ]
