# Generated by Django 2.0.5 on 2018-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20180724_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='acquisitionmethod',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
