# Generated by Django 2.0.5 on 2018-11-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalassetsmanagement', '0010_auto_20181128_0014'),
        ('management', '0005_auto_20180727_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='docs',
            field=models.ManyToManyField(blank=True, to='digitalassetsmanagement.Doc', verbose_name='Documents'),
        ),
    ]
