# Generated by Django 2.0.5 on 2018-07-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20180703_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementunit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto set field', verbose_name='Created in'),
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='description',
            field=models.TextField(blank=True, help_text='The description of Management Unit', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='title',
            field=models.CharField(blank=True, help_text='Title of Management Unit', max_length=256, verbose_name='Title'),
        ),
    ]
