# Generated by Django 2.0.3 on 2018-05-23 21:47

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_old', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=60, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='collection')),
            ],
        ),
    ]
