# Generated by Django 2.0.3 on 2018-06-04 20:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180529_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
