# Generated by Django 2.0.6 on 2018-06-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collection_other_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='author',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='person',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
