# Generated by Django 2.0.5 on 2018-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalassetsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(help_text='The Image File', upload_to='', verbose_name='Image'),
        ),
    ]
