# Generated by Django 2.0.5 on 2018-07-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalassetsmanagement', '0002_auto_20180713_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Ex.: Gelatin negative of the first photo...', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='Ex.: Salgado Negative - 001', max_length=256, verbose_name='Title'),
        ),
    ]
