# Generated by Django 2.0.5 on 2018-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalassetsmanagement', '0003_auto_20180719_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='capture',
            name='image',
            field=models.ImageField(blank=True, help_text='Choose the image whish represents this image', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
