# Generated by Django 2.0.5 on 2018-07-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20180723_1600'),
        ('digitalassetsmanagement', '0004_auto_20180723_1600'),
        ('person', '0004_auto_20180723_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
