# Generated by Django 2.2.7 on 2019-11-25 00:55

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='Auto increment identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False, help_text='Auto set field', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False, help_text='Auto set field', verbose_name='Updated at')),
                ('label', models.CharField(default=None, help_text='Short title', max_length=128, null=True, verbose_name='Label')),
                ('summary', models.CharField(blank=True, default=None, help_text='Brief description', max_length=512, null=True, verbose_name='Summary')),
                ('published', models.BooleanField(db_index=True, default=False, help_text='False by default', verbose_name='Published')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Semi-structured data', null=True, verbose_name='Extra')),
                ('slug', models.SlugField(blank=True, default=None, editable=False, help_text='Generated based on UUID', max_length=128, null=True, unique=True, verbose_name='Slug')),
                ('identifier', models.CharField(blank=True, default=None, help_text='Human readable identifier', max_length=32, null=True, verbose_name='Identifier')),
                ('article', models.TextField(blank=True, help_text='Full description', null=True, verbose_name='Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
