# Generated by Django 2.2.7 on 2019-12-12 17:59

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='identifier',
            new_name='id_human',
        ),
        migrations.AddField(
            model_name='collection',
            name='dimention_items',
            field=models.PositiveIntegerField(blank=True, help_text='Total collection items', null=True, verbose_name='Total Items'),
        ),
        migrations.AddField(
            model_name='collection',
            name='end_date',
            field=models.DateField(blank=True, help_text='Choose an final date', null=True, verbose_name='Final date'),
        ),
        migrations.AddField(
            model_name='collection',
            name='inventary_last_date',
            field=models.DateField(blank=True, help_text='What is the inventary last date?', null=True, verbose_name='Inventary Last Date'),
        ),
        migrations.AddField(
            model_name='collection',
            name='inventary_status',
            field=models.NullBooleanField(help_text='Is there any inventary to this collection?', verbose_name='Inventary Status'),
        ),
        migrations.AddField(
            model_name='collection',
            name='progressbar_custody',
            field=models.PositiveIntegerField(blank=True, help_text='Total processed items', null=True, verbose_name='Processed Items'),
        ),
        migrations.AddField(
            model_name='collection',
            name='progressbar_online',
            field=models.PositiveIntegerField(blank=True, help_text='Total online collection items', null=True, verbose_name='Online Items'),
        ),
        migrations.AddField(
            model_name='collection',
            name='start_date',
            field=models.DateField(blank=True, help_text='Choose a start date', null=True, verbose_name='Initial Date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, help_text='Date this resource was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Semi-structured data in JSON', null=True, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(editable=False, help_text='Sequential identifier', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='label',
            field=models.CharField(default=None, help_text='Short title for this resource', max_length=128, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='published',
            field=models.BooleanField(db_index=True, default=False, help_text='This resource is available to the public', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, default=None, editable=False, help_text='String presented as part of the URL', max_length=128, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, help_text='Date this resource was last updated', verbose_name='Updated at'),
        ),
    ]
