# Generated by Django 2.2.7 on 2019-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20191212_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='progressbar_custody',
        ),
        migrations.AddField(
            model_name='collection',
            name='progressbar_work',
            field=models.PositiveIntegerField(blank=True, help_text='Total processed items', null=True, verbose_name='Percenta'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dimention_items',
            field=models.PositiveIntegerField(blank=True, help_text='Total collection items', null=True, verbose_name='Dimention - Items'),
        ),
    ]
