# Generated by Django 2.2.7 on 2019-12-12 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20191212_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date this resource was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dimention_items',
            field=models.PositiveIntegerField(blank=True, help_text='Total collection items', null=True, verbose_name='Total of items'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='progressbar_online',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage of work available online', null=True, verbose_name='Online Progress Bar'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='progressbar_work',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage of work done', null=True, verbose_name='Work Progress Bar'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date this resource was last updated', verbose_name='Updated at'),
        ),
    ]
