# Generated by Django 2.2.7 on 2019-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20191212_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='inventary_last_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='inventary_status',
        ),
        migrations.AddField(
            model_name='collection',
            name='contract_date',
            field=models.DateField(blank=True, help_text='When the last inventory was completed?', null=True, verbose_name='Inventory Last Date'),
        ),
        migrations.AddField(
            model_name='collection',
            name='contract_status',
            field=models.NullBooleanField(help_text='This collection has any inventory?', verbose_name='Inventory Status'),
        ),
        migrations.AddField(
            model_name='collection',
            name='insurance_date',
            field=models.DateField(blank=True, help_text='When the last inventory was completed?', null=True, verbose_name='Inventory Last Date'),
        ),
        migrations.AddField(
            model_name='collection',
            name='insurance_status',
            field=models.NullBooleanField(help_text='This collection has any inventory?', verbose_name='Inventory Status'),
        ),
        migrations.AddField(
            model_name='collection',
            name='inventory_date',
            field=models.DateField(blank=True, help_text='When the last inventory was completed?', null=True, verbose_name='Inventory Last Date'),
        ),
        migrations.AddField(
            model_name='collection',
            name='inventory_status',
            field=models.NullBooleanField(help_text='This collection has any inventory?', verbose_name='Inventory Status'),
        ),
    ]
