# Generated by Django 2.2.7 on 2019-12-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20191212_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='contract_date',
            field=models.DateField(blank=True, help_text='When the last contract was signed?', null=True, verbose_name='Contract date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='contract_status',
            field=models.NullBooleanField(help_text='This collection has any contract?', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='insurance_date',
            field=models.DateField(blank=True, help_text='When the last insurance was signed?', null=True, verbose_name='Insurance date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='insurance_status',
            field=models.NullBooleanField(help_text='This collection has any insurance?', verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='inventory_date',
            field=models.DateField(blank=True, help_text='When the last inventory was completed?', null=True, verbose_name='Inventory date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='inventory_status',
            field=models.NullBooleanField(help_text='This collection has any inventory?', verbose_name='Inventory'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='progressbar_online',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage of work available online', null=True, verbose_name='Online progress bar'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='progressbar_work',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage of work done', null=True, verbose_name='Work progress bar'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='summary',
            field=models.TextField(blank=True, default=None, help_text='Brief description', max_length=512, null=True, verbose_name='Summary'),
        ),
    ]
