# Generated by Django 2.0.5 on 2018-06-27 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscondition',
            options={'verbose_name_plural': 'Condições de Acesso'},
        ),
        migrations.AlterModelOptions(
            name='aggregationtype',
            options={'verbose_name_plural': 'Tipos de Agregação'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterModelOptions(
            name='descriptionlevel',
            options={'verbose_name_plural': 'Niveis de Descrição'},
        ),
        migrations.AlterModelOptions(
            name='genretag',
            options={'verbose_name_plural': 'Tipologias de Gênero'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='sets',
            options={'verbose_name_plural': 'Conjuntos'},
        ),
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'verbose_name_plural': 'Imagens de apresentação'},
        ),
        migrations.AddField(
            model_name='accesscondition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sets',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
