# Generated by Django 2.0.5 on 2018-07-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('glossary', '0001_initial'),
        ('management', '0001_initial'),
        ('location', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='author',
            field=models.ManyToManyField(blank=True, help_text="Choose some collection's authors", to='person.Person', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='collection',
            name='container',
            field=models.ManyToManyField(blank=True, help_text='Choose containers that compose the collection', to='collection.Container', verbose_name='Containers'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_level',
            field=models.ForeignKey(blank=True, help_text='Choose an Option', null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.DescriptionLevel', verbose_name='Description Level'),
        ),
        migrations.AddField(
            model_name='collection',
            name='genre_tags',
            field=models.ForeignKey(blank=True, help_text='Choose one or more options', null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.GenreTag', verbose_name='Genre Tags'),
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Choose some items that compose this collection. ATTENTION: You can create a container and aggregate items there', to='collection.Item', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='collection',
            name='location_generic',
            field=models.ForeignKey(blank=True, help_text='What is the generic location to the collection?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Location', verbose_name='Generic Location'),
        ),
        migrations.AddField(
            model_name='collection',
            name='management_unit',
            field=models.ForeignKey(blank=True, help_text='What is the management unit concerning to this collection?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.ManagementUnit', verbose_name='Management Unit'),
        ),
        migrations.AddField(
            model_name='collection',
            name='thumbnail',
            field=models.ManyToManyField(blank=True, help_text='Choose some introduction and representative images', to='collection.Thumbnail', verbose_name='Thumbnails'),
        ),
        migrations.AddField(
            model_name='capture',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Choose the image whish represents this capture', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.Thumbnail', verbose_name='Thumbnails'),
        ),
    ]
