# Generated by Django 2.0.5 on 2018-07-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='title',
            field=models.CharField(help_text='Ex.: Container of...', max_length=256, verbose_name='Title'),
        ),
    ]
