# Generated by Django 2.0.5 on 2018-07-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20180709_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(default='No title collection', help_text='Ex.: The complete photo collection of Sebastião Salgado.', max_length=256, verbose_name='Title'),
        ),
    ]
