# Generated by Django 2.0.5 on 2018-07-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_container_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='title',
            field=models.CharField(default='No title collection', help_text='Ex.: The complete photo collection of Sebastião Salgado.', max_length=256, verbose_name='Title'),
        ),
    ]
