# Generated by Django 2.0.5 on 2018-06-27 22:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20180627_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscondition',
            options={'verbose_name': 'Condição de Acesso', 'verbose_name_plural': 'Condições de Acesso'},
        ),
        migrations.AlterModelOptions(
            name='aggregationtype',
            options={'verbose_name': 'Tipo de Agregação', 'verbose_name_plural': 'Tipos de Agregação'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterModelOptions(
            name='descriptionlevel',
            options={'verbose_name': 'Nível de Descrição', 'verbose_name_plural': 'Niveis de Descrição'},
        ),
        migrations.AlterModelOptions(
            name='genretag',
            options={'verbose_name': 'Tipologia de Gênero', 'verbose_name_plural': 'Tipologias de Gênero'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='sets',
            options={'verbose_name': 'Conjunto', 'verbose_name_plural': 'Conjuntos'},
        ),
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'verbose_name': 'Imagem de Apresentação', 'verbose_name_plural': 'Imagens de apresentação'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='abstract',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Ex.: ', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='accesscondition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='accesscondition',
            name='description',
            field=models.TextField(blank=True, help_text='Ex.: ', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='accesscondition',
            name='title_long',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=128, verbose_name='Título Longo'),
        ),
        migrations.AlterField(
            model_name='accesscondition',
            name='title_short',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=64, verbose_name='Título curto'),
        ),
        migrations.AlterField(
            model_name='aggregationtype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do registro'),
        ),
        migrations.AlterField(
            model_name='aggregationtype',
            name='description',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=512, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='aggregationtype',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=256, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='abstract',
            field=models.TextField(blank=True, help_text='Ex.: ', null=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='access_condition',
            field=models.ForeignKey(blank=True, help_text='Ex.: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.AccessCondition', verbose_name='Condição de Acesso'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='access_link',
            field=models.URLField(blank=True, help_text='Ex.: ', null=True, verbose_name='Link de Acesso Digital'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='access_local_status',
            field=models.NullBooleanField(help_text='Ex.: ', verbose_name='Possui acesso local?'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='access_online_status',
            field=models.NullBooleanField(help_text='Ex.: ', verbose_name='Possui acesso online?'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='aggregation_type',
            field=models.ForeignKey(blank=True, help_text='Ex.: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.AggregationType', verbose_name='Tipo de Agregação'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Ex.: ', to='person.Person', verbose_name='Pessoas Relacionadas'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_end',
            field=models.DateTimeField(blank=True, help_text='Ex.: ', null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_end_caption',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=64, null=True, verbose_name='Legenda da Data Final'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_start',
            field=models.DateTimeField(blank=True, help_text='Ex.: ', null=True, verbose_name='Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_start_caption',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=64, null=True, verbose_name='Legenda da Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_level',
            field=models.ForeignKey(blank=True, help_text='Ex.: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.DescriptionLevel', verbose_name='Nível de descrição'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dimension',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Ex.: ', null=True, verbose_name='Dimensões'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='fulltext',
            field=models.TextField(blank=True, help_text='Ex.: ', null=True, verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='genre_tags',
            field=models.ForeignKey(blank=True, help_text='Ex.: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.GenreTag', verbose_name='Gêneros da Coleção'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=64, null=True, unique=True, verbose_name='Identificador Institucional'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id_old',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Ex.: ', null=True, verbose_name='Identificadores Legados'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='inventary_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Ex.: ', null=True, verbose_name='Dados do Inventário'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='inventary_last_date',
            field=models.DateField(blank=True, help_text='Ex.: ', null=True, verbose_name='Data do último inventário'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='inventary_status',
            field=models.NullBooleanField(help_text='Ex.: ', verbose_name='Possui inventário?'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Ex.: ', to='collection.Item', verbose_name='Itens Relacionados'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='items_online',
            field=models.PositiveIntegerField(blank=True, help_text='Ex.: ', null=True, verbose_name='Itens online'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='items_processed',
            field=models.PositiveIntegerField(blank=True, help_text='Ex.: ', null=True, verbose_name='Itens Processados'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='items_total',
            field=models.PositiveIntegerField(blank=True, help_text='Ex.: ', null=True, verbose_name='Total de itens'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='location_generic',
            field=models.ManyToManyField(blank=True, help_text='Ex.: ', to='location.Location', verbose_name='Localização Genérica'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='location_specific',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=256, verbose_name='Localização Específica'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='management_unit',
            field=models.ManyToManyField(blank=True, help_text='Ex.: ', to='management.ManagementUnit', verbose_name='Área de Governança ou Coordenação'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Ex.: ', null=True, verbose_name='Outros Dados Não-Estruturados'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sets',
            field=models.ManyToManyField(blank=True, help_text='Ex.: ', to='collection.Sets', verbose_name='Conjuntos Relacionados'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Ex.: ', max_length=256, null=True, unique=True, verbose_name='Apelido único(slug)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.ManyToManyField(blank=True, help_text='Ex.: ', to='collection.Thumbnail', verbose_name='Imagens de apresentação'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=256, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador Universal do Registro'),
        ),
        migrations.AlterField(
            model_name='descriptionlevel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='descriptionlevel',
            name='description',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=512, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='descriptionlevel',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=256, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do registro'),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='description',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=512, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=256, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Ex.: ', verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=64, null=True, unique=True, verbose_name='Identificador Institucional do Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=256, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador Único Universal'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='abstract',
            field=models.TextField(blank=True, help_text='Ex.: ', null=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='aggregation_type',
            field=models.ForeignKey(blank=True, help_text='Ex.: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.AggregationType', verbose_name='Tipo de Agregação'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='description_level',
            field=models.ForeignKey(blank=True, help_text='Ex.: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.DescriptionLevel', verbose_name='Nível de Descrição'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='id',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=64, null=True, unique=True, verbose_name='Identificador Institucional'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Ex.: ', to='collection.Item', verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='sets_child',
            field=models.ForeignKey(blank=True, help_text='Ex.: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.Sets', verbose_name='Conjuntos Filhos'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=256, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador Único Universal do Conjunto'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do registro'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(blank=True, help_text='Ex.: ', null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: ', max_length=256, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador Único Universal'),
        ),
    ]
