# Generated by Django 2.0.5 on 2018-06-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20180627_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionlevel',
            options={},
        ),
        migrations.AlterField(
            model_name='descriptionlevel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='descriptionlevel',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionlevel',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
