# Generated by Django 2.0.5 on 2018-07-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('collection', '0003_auto_20180711_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='location_generic',
        ),
        migrations.AddField(
            model_name='collection',
            name='location_generic',
            field=models.ForeignKey(blank=True, help_text='What is the generic location to the collection?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Location', verbose_name='Generic Location'),
        ),
    ]
