# Generated by Django 2.0.5 on 2018-06-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20180628_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationtype',
            options={},
        ),
        migrations.AlterField(
            model_name='aggregationtype',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aggregationtype',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='aggregationtype',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
