# Generated by Django 2.0.5 on 2018-07-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20180723_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='author',
            field=models.ManyToManyField(blank=True, help_text="Choose some collection's authors", related_name='collection_author', to='person.Person', verbose_name='Authors'),
        ),
    ]
