# Generated by Django 2.0.5 on 2018-07-24 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20180724_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
        migrations.AddField(
            model_name='container',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
    ]
