# Generated by Django 2.0.5 on 2018-07-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20180703_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date_end',
            field=models.DateField(blank=True, help_text='Choose an final date', null=True, verbose_name='Final date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_start',
            field=models.DateField(blank=True, help_text='Choose a start date', null=True, verbose_name='Initial Date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
