# Generated by Django 2.0.5 on 2018-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20180724_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id_human',
            field=models.CharField(blank=True, default=None, help_text='Institucional Identifier', max_length=64, null=True, unique=True, verbose_name='Institucional ID'),
        ),
    ]
