# Generated by Django 2.0.5 on 2018-07-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20180703_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='fulltext',
            new_name='full_text',
        ),
    ]
