# Generated by Django 2.0.5 on 2018-07-03 22:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20180703_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', primary_key=True, serialize=False, unique=True, verbose_name='Universal Unique Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This is an auto set field', verbose_name='Created in')),
                ('id', models.CharField(blank=True, help_text='Institucional Container Human Identifier', max_length=64, null=True, unique=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Ex.: Container of...', max_length=256, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Ex.: This container is...', null=True, verbose_name='Description')),
                ('aggregation_type', models.ForeignKey(blank=True, help_text='Container Aggregation Type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.AggregationType', verbose_name='Aggregation Type')),
                ('container_child', models.ForeignKey(blank=True, help_text='Choose child containers to aggregate to this one', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.Container', verbose_name='Child containers')),
                ('description_level', models.ForeignKey(blank=True, help_text='Choose a description level to this container', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.DescriptionLevel', verbose_name='Description level')),
                ('items', models.ManyToManyField(blank=True, help_text='Itens that composes the container', to='collection.Item', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
        ),
        migrations.RemoveField(
            model_name='sets',
            name='aggregation_type',
        ),
        migrations.RemoveField(
            model_name='sets',
            name='description_level',
        ),
        migrations.RemoveField(
            model_name='sets',
            name='items',
        ),
        migrations.RemoveField(
            model_name='sets',
            name='sets_child',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sets',
        ),
        migrations.DeleteModel(
            name='Sets',
        ),
        migrations.AddField(
            model_name='collection',
            name='container',
            field=models.ForeignKey(blank=True, help_text='Choose containers that compose the collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.Container', verbose_name='Containers'),
        ),
    ]
