# Generated by Django 2.0.5 on 2018-07-27 19:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20180727_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id_human',
            field=models.CharField(blank=True, default=None, help_text='Institucional Identifier', max_length=64, null=True, unique=True, verbose_name='Institucional ID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id_old',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='Legacy Identifiers', null=True, verbose_name='Old IDs'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(default=None, help_text='Ex.: The title of this record', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='container',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='container',
            name='title',
            field=models.CharField(default=None, help_text='Ex.: The title of this record', max_length=256, verbose_name='Title'),
        ),
    ]
