# Generated by Django 2.0.5 on 2018-07-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0007_auto_20180727_1626'),
        ('collection', '0010_auto_20180727_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='genre_tags',
        ),
        migrations.AddField(
            model_name='collection',
            name='genre_tags',
            field=models.ManyToManyField(blank=True, help_text='Choose one or more options', to='glossary.GenreTag', verbose_name='Genre Tags'),
        ),
    ]
