# Generated by Django 2.0.5 on 2018-07-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20180703_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='container_child',
        ),
        migrations.AddField(
            model_name='container',
            name='container_child',
            field=models.ManyToManyField(blank=True, help_text='Choose child containers to aggregate to this one', related_name='_container_container_child_+', to='collection.Container', verbose_name='Child containers'),
        ),
    ]
