# Generated by Django 2.0.5 on 2018-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20180731_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, default=None, help_text='Ex.: The title of this record', max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='container',
            name='title',
            field=models.CharField(blank=True, default=None, help_text='Ex.: The title of this record', max_length=256, null=True, verbose_name='Title'),
        ),
    ]
