# Generated by Django 2.0.5 on 2018-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20180703_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='location_specific',
            field=models.CharField(blank=True, help_text='What is the specific location to this collection?', max_length=256, null=True, verbose_name='Specific Location'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: The complete photo collection of Sebastião Salgado.', max_length=256, null=True, verbose_name='Title'),
        ),
    ]
