# Generated by Django 2.0.5 on 2018-10-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_auto_20180802_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='capture',
            field=models.ManyToManyField(blank=True, help_text='Choose some introduction and representative images', to='digitalassetsmanagement.Capture', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True, help_text='Ex.: This container is...', null=True, verbose_name='Full Description'),
        ),
    ]
