# Generated by Django 2.0.5 on 2018-07-05 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_auto_20180705_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto set field', verbose_name='Created in')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', primary_key=True, serialize=False, unique=True, verbose_name='Universal Unique Identifier')),
                ('title', models.CharField(blank=True, help_text='Ex.: The capture title', max_length=256, null=True, verbose_name='Title')),
                ('thumbnail', models.ManyToManyField(blank=True, help_text='Choose the image whish represents this capture', to='collection.Thumbnail', verbose_name='Thumbnails')),
            ],
            options={
                'verbose_name': 'Capture',
                'verbose_name_plural': 'Captures',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='capture',
            field=models.ManyToManyField(blank=True, help_text='Capture(s) taked from this item.', to='collection.Capture', verbose_name='Capture(s)'),
        ),
    ]
