# Generated by Django 2.0.5 on 2018-07-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20180705_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='capture',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Choose the image whish represents this capture', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.Thumbnail', verbose_name='Thumbnails'),
        ),
    ]
