# Generated by Django 2.0.5 on 2018-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20180705_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, help_text='Ex.: Salgado Negative - 001', max_length=256, verbose_name='Title'),
        ),
    ]
