# Generated by Django 2.0.5 on 2018-07-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20180705_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='container',
        ),
        migrations.AddField(
            model_name='collection',
            name='container',
            field=models.ManyToManyField(blank=True, help_text='Choose containers that compose the collection', to='collection.Container', verbose_name='Containers'),
        ),
    ]
