# Generated by Django 2.0.5 on 2018-11-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_acquisition_docs'),
        ('collection', '0015_collection_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='acquisitions',
            field=models.ManyToManyField(blank=True, to='management.Acquisition', verbose_name='Acquisitions'),
        ),
    ]
