# Generated by Django 2.0.5 on 2018-07-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20180705_1627'),
        ('collection', '0016_auto_20180705_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='management_unit',
        ),
        migrations.AddField(
            model_name='collection',
            name='management_unit',
            field=models.ForeignKey(blank=True, help_text='What is the management unit concerning to this collection?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.ManagementUnit', verbose_name='Management Unit'),
        ),
    ]
