# Generated by Django 2.0.5 on 2018-07-13 20:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id_auto_series', models.BigAutoField(editable=False, help_text='Auto Increment ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', unique=True, verbose_name='Universal Unique Identifier')),
                ('id_human', models.CharField(blank=True, help_text='Institucional Identifier', max_length=64, null=True, unique=True, verbose_name='Institucional ID')),
                ('title', models.CharField(default='', help_text='Ex.: Sebastião Salgado - first images', max_length=256, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Ex.: exhibition-sebastiao-salgado-first-images', max_length=256, null=True, unique=True, verbose_name='Slug')),
                ('abstract', models.TextField(blank=True, help_text='Ex.: This exhibition is composed by...', null=True, verbose_name='Abstract')),
                ('full_text', models.TextField(blank=True, help_text='Ex.: This exhibition is about...', null=True, verbose_name='Full Text')),
                ('date_start', models.DateField(blank=True, help_text='Choose a start date', null=True, verbose_name='Initial Date')),
                ('date_end', models.DateField(blank=True, help_text='Choose an final date', null=True, verbose_name='Final date')),
                ('link', models.URLField(blank=True, help_text='Do you have some online link to this edition?', null=True, verbose_name='Link')),
                ('team', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Infos about the exhibition team', null=True, verbose_name='Team')),
                ('catalog', models.ManyToManyField(blank=True, help_text='Is there an catalog about the exhibition?', related_name='exhibitionCatalog', to='publication.Publication', verbose_name='Catalog(s)')),
                ('location', models.ForeignKey(blank=True, help_text='What is the exhibition edition location?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Location', verbose_name='Location')),
                ('publication', models.ManyToManyField(blank=True, help_text='Is there any other publications about the exhibition?', related_name='exhibitionPublication', to='publication.Publication', verbose_name='Publication(s)')),
            ],
            options={
                'verbose_name': 'Exhibition',
                'verbose_name_plural': 'Exhibitions',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionEdition',
            fields=[
                ('id_auto_series', models.BigAutoField(editable=False, help_text='Auto Increment ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', unique=True, verbose_name='Universal Unique Identifier')),
                ('id_human', models.CharField(blank=True, help_text='Institucional Identifier', max_length=64, null=True, unique=True, verbose_name='Institucional ID')),
                ('title', models.CharField(help_text='Ex.: Summer photo protests - 1st edition', max_length=256, verbose_name='Title')),
                ('full_text', models.TextField(blank=True, help_text='Ex.: This exhibition is about...', null=True, verbose_name='Full Text')),
                ('date_start', models.DateField(blank=True, help_text='Choose a start date', null=True, verbose_name='Initial Date')),
                ('date_end', models.DateField(blank=True, help_text='Choose an final date', null=True, verbose_name='Final date')),
                ('team', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Infos about the edition team', null=True, verbose_name='Team')),
                ('exhibition', models.ForeignKey(blank=True, help_text='The main Exhibition source from this edition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exhibition.Exhibition', verbose_name='Original Exhibition')),
                ('location', models.ForeignKey(blank=True, help_text='What is the location where occurs this exhibition edition?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Exhibition Edition',
                'verbose_name_plural': 'Exhibition Editions',
            },
        ),
    ]
