# Generated by Django 2.0.5 on 2018-07-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitionedition',
            options={'verbose_name': 'Exhibition Edition', 'verbose_name_plural': 'Exhibition Editions'},
        ),
        migrations.RemoveField(
            model_name='exhibitionedition',
            name='description',
        ),
        migrations.AddField(
            model_name='exhibitionedition',
            name='full_text',
            field=models.TextField(blank=True, help_text='Ex.: This exhibition is about...', null=True, verbose_name='Full Text'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='full_text',
            field=models.TextField(blank=True, help_text='Ex.: This exhibition is about...', null=True, verbose_name='Full Text'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(default='', help_text='Ex.: Sebastião Salgado - first images', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='exhibitionedition',
            name='exhibition',
            field=models.ForeignKey(blank=True, help_text='The main Exhibition source from this edition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exhibition.Exhibition', verbose_name='Original Exhibition'),
        ),
    ]
