# Generated by Django 2.0.5 on 2018-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0006_auto_20180727_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(blank=True, default=None, help_text='Ex.: The title of this record', max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='exhibitionedition',
            name='title',
            field=models.CharField(blank=True, default=None, help_text='Ex.: The title of this record', max_length=256, null=True, verbose_name='Title'),
        ),
    ]
