# Generated by Django 2.0.5 on 2018-10-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0008_exhibition_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='capture',
            field=models.ManyToManyField(blank=True, help_text='Choose some introduction and representative images', to='digitalassetsmanagement.Capture', verbose_name='Image'),
        ),
    ]
