# Generated by Django 2.0.1 on 2018-01-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.CharField(help_text='Código de identificação', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('resumo', models.TextField(help_text='Faça uma breve descrição da coleção', max_length=300)),
                ('num_itens', models.IntegerField(blank=True, null=True)),
                ('num_itens_online', models.IntegerField(blank=True, null=True)),
                ('aquisicao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Morreu')),
                ('bio_short', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('col', 'Coleção'), ('cnj', 'Conjunto'), ('obr', 'Obra'), ('ens', 'Ensaio'), ('lot', 'Lote')], default='col', help_text='Tipo de agrupamento', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='colecao',
            name='pessoas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia.Pessoa'),
        ),
        migrations.AddField(
            model_name='colecao',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia.Tipo'),
        ),
    ]
