# Generated by Django 2.0.1 on 2018-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colecao',
            options={'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterField(
            model_name='colecao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Coleção', 'Coleção'), ('Conjunto', 'Conjunto'), ('Obra', 'Obra'), ('Ensaio', 'Ensaio'), ('Lote', 'Lote')], help_text='Tipo de agrupamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bio_short',
            field=models.TextField(max_length=300, verbose_name='Biografia curta'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Falecimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
