# Generated by Django 2.0.1 on 2018-02-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_auto_20180201_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colecao',
            options={'ordering': ['id'], 'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterField(
            model_name='colecao',
            name='aquisicao',
            field=models.DateField(verbose_name='Data de Aquisição'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nome'),
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='pessoas',
        ),
        migrations.AddField(
            model_name='colecao',
            name='pessoas',
            field=models.ManyToManyField(to='guia.Pessoa'),
        ),
    ]
