# Generated by Django 2.0.1 on 2018-02-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_auto_20180201_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bio_short',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Biografia curta'),
        ),
    ]
