# Generated by Django 2.0.1 on 2018-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0004_auto_20180201_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['name'], 'verbose_name': 'Pessoa'},
        ),
        migrations.AlterField(
            model_name='colecao',
            name='pessoas',
            field=models.ManyToManyField(blank=True, null=True, to='guia.Pessoa'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='resumo',
            field=models.TextField(blank=True, help_text='Faça uma breve descrição da coleção', max_length=300, null=True),
        ),
    ]
