# Generated by Django 2.0.1 on 2018-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0005_auto_20180201_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='pessoas',
            field=models.ManyToManyField(blank=True, to='guia.Pessoa'),
        ),
    ]
