# Generated by Django 2.0.1 on 2018-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0006_auto_20180201_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='local_nascimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade natal'),
        ),
    ]
