# Generated by Django 2.0.1 on 2018-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0007_pessoa_local_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='estado_nascimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado natal'),
        ),
    ]
