# Generated by Django 2.0.1 on 2018-02-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0008_pessoa_estado_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='aquisicao',
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='name',
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estado_nascimento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='local_nascimento',
        ),
        migrations.AddField(
            model_name='colecao',
            name='area_ims',
            field=models.CharField(choices=[('Acervo', 'Acervo'), ('Biblioteca', 'Biblioteca'), ('Fotografia', 'Fotografia'), ('Iconografia', 'Iconografia'), ('Literatura', 'Literatura'), ('Música', 'Música')], default='Acervos', max_length=20, verbose_name='Área responsável'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colecao',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AddField(
            model_name='colecao',
            name='entry_model',
            field=models.CharField(blank=True, choices=[('Acumulação', 'Acumulação'), ('Comodato', 'Comodato'), ('Compra', 'Compra'), ('Doação', 'Doação'), ('Transferência', 'Transferência')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='colecao',
            name='observ',
            field=models.TextField(blank=True, help_text='Insira observações sobre a coleção', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='colecao',
            name='old_id',
            field=models.CharField(blank=True, help_text='Outros códigos de identificação', max_length=140, null=True, verbose_name='Códigos anteriores'),
        ),
        migrations.AddField(
            model_name='colecao',
            name='title',
            field=models.CharField(default='Titulo', max_length=140, verbose_name='Títuto'),
            preserve_default=False,
        ),
    ]
