# Generated by Django 2.0.1 on 2018-02-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0010_auto_20180201_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colecao',
            old_name='observ',
            new_name='entry_obs',
        ),
        migrations.AlterField(
            model_name='colecao',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrada'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='entry_model',
            field=models.CharField(blank=True, choices=[('Acumulação', 'Acumulação'), ('Comodato', 'Comodato'), ('Compra', 'Compra'), ('Doação', 'Doação'), ('Transferência', 'Transferência')], max_length=20, null=True, verbose_name='Modo de entrada'),
        ),
    ]
