# Generated by Django 2.0.1 on 2018-02-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0013_auto_20180201_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Títuto'),
        ),
    ]
