# Generated by Django 2.0.1 on 2018-02-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0016_auto_20180201_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ocupação'),
        ),
    ]
