# Generated by Django 2.0.1 on 2018-02-21 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0017_auto_20180201_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador do lote de controle patrimonial', primary_key=True, serialize=False, verbose_name='Identificador')),
                ('entry_model', models.CharField(blank=True, choices=[('Acumulação', 'Acumulação'), ('Comodato', 'Comodato'), ('Compra', 'Compra'), ('Doação', 'Doação'), ('Transferência', 'Transferência')], max_length=200, null=True, verbose_name='Modo de entrada')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Data de entrada')),
                ('entry_obs', models.TextField(blank=True, help_text='Insira observações sobre a coleção', max_length=1000, null=True, verbose_name='Observações')),
                ('colecao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia.Colecao')),
            ],
        ),
    ]
