# Generated by Django 2.0.1 on 2018-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0018_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Duração'),
        ),
    ]
