# Generated by Django 2.0.1 on 2018-02-26 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0019_colecao_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='colecao',
            new_name='collections',
        ),
        migrations.AddField(
            model_name='colecao',
            name='composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia.Lote'),
        ),
    ]
