# Generated by Django 2.0.1 on 2018-02-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0020_auto_20180226_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='collections',
            new_name='colecao',
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='composition',
        ),
    ]
