# Generated by Django 2.0.1 on 2018-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0021_auto_20180226_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='entry_obs',
            field=models.TextField(blank=True, help_text='Insira observações sobre a coleção', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='resumo',
            field=models.TextField(blank=True, help_text='Faça uma breve descrição da coleção', null=True),
        ),
    ]
