# Generated by Django 2.0.1 on 2018-03-08 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0022_auto_20180305_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome')),
                ('date_of_begin', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sobre')),
            ],
            options={
                'verbose_name': 'Exposição',
                'ordering': ['date_of_begin'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome')),
                ('date_of_release', models.DateField(blank=True, null=True, verbose_name='Data de lançamento')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sobre')),
            ],
            options={
                'verbose_name': 'Publicações',
                'ordering': ['date_of_release'],
            },
        ),
    ]
