# Generated by Django 2.0.1 on 2018-03-14 18:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0023_exhibition_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['date_of_begin'], 'verbose_name': 'Exposição', 'verbose_name_plural': 'Exposições'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['date_of_release'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AddField(
            model_name='colecao',
            name='teste_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='hello', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colecao',
            name='teste_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='helloj'),
            preserve_default=False,
        ),
    ]
