# Generated by Django 2.0.1 on 2018-03-14 18:15

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0024_auto_20180314_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='teste_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='teste_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
