# Generated by Django 2.0.1 on 2018-03-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0025_auto_20180314_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='teste_array',
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='teste_json',
        ),
    ]
