# Generated by Django 2.0.3 on 2018-03-23 20:19

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.CharField(help_text='Código de identificação', max_length=20, primary_key=True, serialize=False, verbose_name='Código (UID)')),
                ('old_id', models.CharField(blank=True, help_text='Outros códigos de identificação', max_length=140, null=True, verbose_name='Códigos anteriores')),
                ('title', models.CharField(max_length=300, verbose_name='Títuto')),
                ('area_ims', models.CharField(choices=[('Acervo', 'Acervo'), ('Biblioteca', 'Biblioteca'), ('Fotografia', 'Fotografia'), ('Iconografia', 'Iconografia'), ('Literatura', 'Literatura'), ('Música', 'Música')], max_length=200, verbose_name='Área responsável')),
                ('entry_model', models.CharField(blank=True, choices=[('Acumulação', 'Acumulação'), ('Comodato', 'Comodato'), ('Compra', 'Compra'), ('Doação', 'Doação'), ('Transferência', 'Transferência')], max_length=200, null=True, verbose_name='Modo de entrada')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Data de entrada')),
                ('entry_obs', models.TextField(blank=True, help_text='Insira observações sobre a coleção', null=True, verbose_name='Observações')),
                ('resumo', models.TextField(blank=True, help_text='Faça uma breve descrição da coleção', null=True)),
                ('num_itens', models.IntegerField(blank=True, null=True)),
                ('num_itens_online', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(null=True, verbose_name='Duração')),
                ('teste_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('teste_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome')),
                ('date_of_begin', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sobre')),
            ],
            options={
                'verbose_name_plural': 'Exposições',
                'verbose_name': 'Exposição',
                'ordering': ['date_of_begin'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificador do lote de controle patrimonial', primary_key=True, serialize=False, verbose_name='Identificador')),
                ('entry_model', models.CharField(blank=True, choices=[('Acumulação', 'Acumulação'), ('Comodato', 'Comodato'), ('Compra', 'Compra'), ('Doação', 'Doação'), ('Transferência', 'Transferência')], max_length=200, null=True, verbose_name='Modo de entrada')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Data de entrada')),
                ('entry_obs', models.TextField(blank=True, help_text='Insira observações sobre a coleção', max_length=1000, null=True, verbose_name='Observações')),
                ('colecao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia.Colecao')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Falecimento')),
                ('ocupacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ocupação')),
                ('bio_short', models.TextField(blank=True, max_length=300, null=True, verbose_name='Biografia curta')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome')),
                ('date_of_release', models.DateField(blank=True, null=True, verbose_name='Data de lançamento')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sobre')),
            ],
            options={
                'verbose_name_plural': 'Publicações',
                'verbose_name': 'Publicação',
                'ordering': ['date_of_release'],
            },
        ),
        migrations.AddField(
            model_name='colecao',
            name='pessoas',
            field=models.ManyToManyField(blank=True, to='guia.Pessoa'),
        ),
    ]
