# Generated by Django 2.0.5 on 2018-07-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Ex.: Launch of new publication...', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(help_text='Ex.: course, workshop, show, launching', max_length=256, verbose_name='Title'),
        ),
    ]
