# Generated by Django 2.0.5 on 2018-11-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.IntegerField(blank=True, help_text='Number of participants', null=True, verbose_name='Audience'),
        ),
    ]
