# Generated by Django 2.0.5 on 2018-06-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Pessoas'},
        ),
    ]
