# Generated by Django 2.0.5 on 2018-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, help_text='Biological sex gender', max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
