# Generated by Django 2.0.5 on 2018-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(help_text='Ex.: Mr. Louis-Jacques-Mandé Daguerre', max_length=256, verbose_name='Title'),
        ),
    ]
