# Generated by Django 2.0.5 on 2018-07-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='title_idex',
            new_name='title_index',
        ),
    ]
