# Generated by Django 2.0.5 on 2018-07-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180627_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
