# Generated by Django 2.0.5 on 2018-07-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180719_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_feature',
            field=models.NullBooleanField(help_text='This is a featured person?', verbose_name='Authority Member'),
        ),
    ]
