# Generated by Django 2.0.5 on 2018-08-27 20:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitalassetsmanagement', '0008_auto_20180802_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_auto_series', models.BigAutoField(editable=False, help_text='Auto Increment ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', unique=True, verbose_name='Universal Unique Identifier')),
                ('title', models.CharField(blank=True, default=None, help_text='Ex.: The title of this record', max_length=256, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug')),
                ('full_text', models.TextField(blank=True, help_text='Ex.: Welcome to Guia...', null=True, verbose_name='Content')),
                ('capture', models.ManyToManyField(blank=True, help_text='Choose some introduction and representative images', to='digitalassetsmanagement.Capture', verbose_name='Capture')),
            ],
            options={
                'verbose_name': 'Home Post',
                'verbose_name_plural': 'Home Posts',
            },
        ),
    ]
