# Generated by Django 2.0.5 on 2018-07-14 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCondition',
            fields=[
                ('id_auto_series', models.BigAutoField(editable=False, help_text='Auto Increment ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', unique=True, verbose_name='Universal Unique Identifier')),
                ('title_short', models.CharField(help_text='Ex.: Full Free, Partial, Retricted, etc.', max_length=64, verbose_name='Access')),
                ('title_long', models.CharField(blank=True, help_text='Ex.: Partial - copyright.', max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Ex.: Some documents here have copyright...', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Access Condition',
                'verbose_name_plural': 'Access Conditions',
            },
        ),
        migrations.CreateModel(
            name='AggregationType',
            fields=[
                ('id_auto_series', models.BigAutoField(editable=False, help_text='Auto Increment ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', unique=True, verbose_name='Universal Unique Identifier')),
                ('title', models.CharField(help_text='Ex.: collection, archive, etc', max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, help_text='Ex.: the collection is a group of...', max_length=512, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Aggregation Type',
                'verbose_name_plural': 'Aggregations Type',
            },
        ),
        migrations.CreateModel(
            name='DescriptionLevel',
            fields=[
                ('id_auto_series', models.BigAutoField(editable=False, help_text='Auto Increment ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', unique=True, verbose_name='Universal Unique Identifier')),
                ('title', models.CharField(help_text='Ex.: basic - 0', max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, help_text='The description of level type...', max_length=512, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Description level',
                'verbose_name_plural': 'Description levels',
            },
        ),
        migrations.CreateModel(
            name='GenreTag',
            fields=[
                ('id_auto_series', models.BigAutoField(editable=False, help_text='Auto Increment ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', unique=True, verbose_name='Universal Unique Identifier')),
                ('title', models.CharField(help_text='Ex.: photo, picture, draw, etc', max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, help_text='Ex.: A photo is all kind part or entire piece of an image produced by a camera.', max_length=512, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Genre Tag',
                'verbose_name_plural': 'Genre Tags',
            },
        ),
    ]
