# Generated by Django 2.0.5 on 2018-07-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscondition',
            name='title_short',
            field=models.CharField(help_text='Ex.: Full Free, Partial, Retricted, etc.', max_length=64, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='aggregationtype',
            name='title',
            field=models.CharField(help_text='Ex.: collection, archive, etc', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='descriptionlevel',
            name='title',
            field=models.CharField(help_text='Ex.: basic - 0', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='title',
            field=models.CharField(help_text='Ex.: photo, picture, draw, etc', max_length=256, verbose_name='Title'),
        ),
    ]
