# Generated by Django 2.0.5 on 2018-07-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_auto_20180719_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscondition',
            name='title',
            field=models.CharField(default='No title collection', help_text='Ex.: The complete photo collection of Sebastião Salgado.', max_length=256, verbose_name='Title'),
        ),
    ]
