# Generated by Django 2.0.5 on 2018-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_auto_20180719_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscondition',
            name='title_long',
            field=models.CharField(blank=True, help_text='Ex.: Partial - copyright.', max_length=128, verbose_name='Condition'),
        ),
    ]
