# Generated by Django 2.0.5 on 2018-07-24 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0005_auto_20180723_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscondition',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
        migrations.AddField(
            model_name='aggregationtype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
        migrations.AddField(
            model_name='descriptionlevel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
        migrations.AddField(
            model_name='genretag',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Auto set field', verbose_name='Created in'),
        ),
    ]
