# Generated by Django 2.0.5 on 2018-07-11 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0002_auto_20180709_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This is an auto set field', primary_key=True, serialize=False, unique=True, verbose_name='Universal Unique Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This is an auto set field', verbose_name='Created in')),
                ('id', models.CharField(blank=True, help_text='Institucional Collection Human Identifier', max_length=64, null=True, unique=True, verbose_name='ID')),
                ('title', models.CharField(default='No title collection', help_text='Ex.: The complete photo collection of Sebastião Salgado.', max_length=256, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Ex.: book-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug')),
                ('abstract', models.TextField(blank=True, help_text='Ex.: This publication is composed by...', null=True, verbose_name='Abstract')),
                ('full_text', models.TextField(blank=True, help_text='Ex.: The book serie is...', null=True, verbose_name='Full Text')),
                ('date_released', models.DateField(blank=True, help_text='Choose the released date', null=True, verbose_name='Released Date')),
                ('author', models.ManyToManyField(blank=True, help_text="Choose some collection's authors", related_name='personAuthor', to='person.Person', verbose_name='Authors')),
                ('publisher', models.ManyToManyField(blank=True, help_text="Choose some collection's authors", related_name='personPublisher', to='person.Person', verbose_name='Authors')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
