# Generated by Django 2.0.5 on 2018-07-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_auto_20180724_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='pages',
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Choose some Author(s)', related_name='personAuthor', to='person.Person', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ManyToManyField(blank=True, help_text='Choose some Publisher', related_name='personPublisher', to='person.Person', verbose_name='Publisher(s)'),
        ),
    ]
