# Generated by Django 2.0.5 on 2018-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20180724_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default=None, help_text='Ex.: The title of this record', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Ex.: complete-collection-sebastiao-salgado', max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
